@baseUrl = http://localhost:3000/api/artifacts

### GET all artifacts
GET {{baseUrl}}
Content-Type: application/json

### POST create new artifact
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Harmonijka Testowa",
  "description": "Magiczna harmonijka",
  "owner": "69d7730a4e6d01df631b4754"
}

### GET single artifact
GET {{baseUrl}}/69d7790d233f66acb4df5f3e
Content-Type: application/json

### PUT update artifact
PUT {{baseUrl}}/69d7790d233f66acb4df5f3e
Content-Type: application/json

{
  "description": "Zmieniony opis harmonijki"
}

### DELETE artifact
DELETE {{baseUrl}}/69d7790d233f66acb4df5f3e
Content-Type: application/json