@baseUrl = http://localhost:3000/api/characters

### GET all characters
GET {{baseUrl}}
Content-Type: application/json

### POST create new character
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Muminek Testowy",
  "description": "Opis Muminka Testowego",
  "species": "Muminek",
  "isHibernating": false
}

### GET single character
GET {{baseUrl}}/69d77907233f66acb4df5f3d
Content-Type: application/json

### PUT update character
PUT {{baseUrl}}/69d77aaa9e2c7aad6d6da325
Content-Type: application/json

{
  "species": "Inny",
  "isHibernating": true
}

### DELETE character
DELETE {{baseUrl}}/69d7730a4e6d01df631b4754
Content-Type: application/json